# Generated by Django 3.0.4 on 2020-08-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(upload_to='EventPosters')),
                ('title', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('description', models.TextField(max_length=350)),
                ('status', models.CharField(choices=[('upcoming', 'upcoming'), ('completed', 'completed')], default='upcoming', max_length=10)),
                ('report', models.TextField(blank=True)),
                ('images_url', models.URLField(blank=True)),
                ('event_image1', models.ImageField(blank=True, upload_to='EventImages')),
                ('event_image2', models.ImageField(blank=True, upload_to='EventImages')),
                ('event_image3', models.ImageField(blank=True, upload_to='EventImages')),
            ],
        ),
    ]
