# Generated by Django 3.0.4 on 2020-08-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_auto_20200806_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_fee',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
