# Generated by Django 3.0.7 on 2020-07-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committie', '0002_auto_20200723_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committie',
            name='Designation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='committie',
            name='Linkedin',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='committie',
            name='Quote',
            field=models.CharField(max_length=100),
        ),
    ]
