# Generated by Django 3.0.7 on 2020-07-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committie', '0003_auto_20200723_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committie',
            name='Quote',
            field=models.CharField(max_length=200),
        ),
    ]
