# Generated by Django 3.0.7 on 2020-07-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committie', '0004_auto_20200724_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committie',
            name='Designation',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('Joint Secretary', 'Joint Secretary'), ('Sponsorship Head', ' Sponsorship Head'), ('Joint Sponsorship Head', 'Joint Sponsorship Head'), ('PR Head', 'PR Head'), ('Joint PR', 'Joint PR'), ('Creative Head', 'Creative Head'), ('Joint Creative', 'Joint Creative'), ('Technical Head', 'Technical Head'), ('Joint Technical', 'Joint Technical'), ('Organizing Head', 'Organizing Head'), ('Joint Organizing', 'Joint Organizing'), ('Magazine Head', 'Magazine Head'), ('Joint Magzine', 'Joint Magzine'), ('Treasurer', 'Treasurer'), ('Membership', 'Membership')], default='', max_length=50),
        ),
    ]
