# Generated by Django 3.0.4 on 2020-08-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_pic', models.ImageField(upload_to='BlogCovers')),
                ('title', models.CharField(max_length=500)),
                ('writer_pic', models.ImageField(upload_to='UserPhotos')),
                ('writer_name', models.CharField(max_length=300)),
                ('insta_id', models.URLField(blank=True)),
                ('twitter_id', models.URLField(blank=True)),
                ('linkedin_id', models.URLField(blank=True)),
                ('date_of_article', models.DateField()),
                ('article', models.TextField()),
            ],
        ),
    ]
