# Generated by Django 3.0.4 on 2020-08-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='writer_pic',
            field=models.ImageField(blank=True, upload_to='UserPhotos'),
        ),
    ]
