# Generated by Django 3.0.4 on 2020-07-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslider',
            name='short_description',
            field=models.TextField(),
        ),
    ]
