# Generated by Django 3.1 on 2020-08-09 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200718_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselslider',
            name='short_description',
        ),
    ]
