# Generated by Django 3.0.4 on 2020-08-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Committie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committie',
            name='Designation',
            field=models.CharField(choices=[('Staff Coordinator', 'Staff Coordinator'), ('President', 'President'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('Joint Secretary', 'Joint Secretary'), ('Sponsorship Head', ' Sponsorship Head'), ('Joint Sponsorship', 'Joint Sponsorship'), ('PR Head', 'PR Head'), ('Joint PR', 'Joint PR'), ('Creative Head', 'Creative Head'), ('Joint Creative', 'Joint Creative'), ('Technical Head', 'Technical Head'), ('Joint Technical', 'Joint Technical'), ('Organizing Head', 'Organizing Head'), ('Joint Organizing', 'Joint Organizing'), ('Magazine Head', 'Magazine Head'), ('Joint Magazine', 'Joint Magazine'), ('Treasurer', 'Treasurer'), ('Membership', 'Membership')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='committie',
            name='Image',
            field=models.ImageField(upload_to='members/'),
        ),
    ]
