# Generated by Django 3.0.7 on 2020-07-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committie',
            old_name='image',
            new_name='Image',
        ),
        migrations.AddField(
            model_name='committie',
            name='Category',
            field=models.CharField(choices=[('Faculty', 'Faculty'), ('Student', 'Student')], default='Student', max_length=10),
        ),
        migrations.AddField(
            model_name='committie',
            name='Designation',
            field=models.CharField(default='member', max_length=50),
        ),
        migrations.AddField(
            model_name='committie',
            name='Linkedin',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='committie',
            name='Quote',
            field=models.CharField(default='', max_length=100),
        ),
    ]
